# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

seqFregments <- function(strings, k = 2L) {
    .Call('_MIcalc_seqFregments', PACKAGE = 'MIcalc', strings, k)
}

